name: nanopore
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - minimap2=2.26
  - samtools=1.17
  - fastqc
  - nanoplot
  - pysam
  - pandas
  - numpy
  - biopython
# Dorado (v1.4.0) is installed separately from Oxford Nanopore.
